import React,{useEffect,useMemo,useState}from'react';
import'./edit.css';

const cookie=name=>document.cookie.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.split('=').slice(1).join('=')||'';
async function request(url,options={}){const response=await fetch(url,{...options,headers:{'Content-Type':'application/json','X-CSRFToken':decodeURIComponent(cookie('csrftoken')),...options.headers}});const data=await response.json();if(!response.ok||data.success===false)throw new Error(data.error||'Request failed.');return data}
const fields=[['name','Business name'],['phone','Phone'],['email','Email'],['address','Address'],['website','Website'],['category','Category'],['area','Area'],['city','City'],['province','Province / State'],['country','Country'],['latitude','Latitude'],['longitude','Longitude']];

export default function ResultsPage(){
 const[data,setData]=useState(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState([]),[editing,setEditing]=useState(null),[saving,setSaving]=useState(false);const id=new URLSearchParams(location.search).get('search');
 const load=()=>request(id?`/api/searches/${id}/`:'/api/searches/latest/').then(d=>setData(d.search)).catch(e=>setError(e.message));useEffect(load,[id]);
 const rows=useMemo(()=>data?data.results.filter(x=>[x.name,x.phone,x.email,x.address].join(' ').toLowerCase().includes(query.toLowerCase())):[],[data,query]);
 const endpoint=resultId=>`/api/searches/${data.id}/results/${resultId}/`;
 const save=async e=>{e.preventDefault();setSaving(true);setError('');try{const d=await request(endpoint(editing.id),{method:'PATCH',body:JSON.stringify(editing)});setData({...data,results:data.results.map(x=>x.id===d.result.id?d.result:x)});setEditing(null)}catch(e){setError(e.message)}finally{setSaving(false)}};
 const remove=async item=>{if(!confirm(`Delete ${item.name}? This will update the JSON file.`))return;try{await request(endpoint(item.id),{method:'DELETE'});const results=data.results.filter(x=>x.id!==item.id);setData({...data,results,result_count:results.length});setSelected(selected.filter(x=>x!==item.id))}catch(e){setError(e.message)}};
 if(error&&!data)return <div className="panel alert">{error}</div>;if(!data)return <div className="wait-screen"><div className="loading-box"><i className="spinner"/><b>Loading saved business details…</b></div></div>;
 const google=x=>x.latitude&&x.longitude?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(x.latitude+','+x.longitude)}`:x.google_maps_url;
 const exportUrl=(type,all=false)=>`/export/${type}/?search=${data.id}${!all&&selected.length?'&ids='+selected.join(','):''}`;
 return <><div className="heading"><div><h1>Search results</h1><p>{data.category} in {data.city}, {data.country} · {data.result_count} found</p></div><a className="outline" href="/">＋ New search</a></div>{error&&<div className="alert">{error}</div>}<section className="panel"><div className="filters"><input placeholder="Search name, phone, email or address" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="export"><span>{selected.length} selected</span><a href={exportUrl('csv')}>Export CSV</a><a href={exportUrl('excel')}>Export Excel</a><a className="primary" href={exportUrl('excel',true)}>Export all</a></div><div className="table"><table><thead><tr><th></th><th>#</th><th>Business</th><th>Phone</th><th>Email</th><th>Address</th><th>Website</th><th>Category</th><th>Google Maps</th><th>Actions</th></tr></thead><tbody>{rows.map((x,i)=><tr key={x.id}><td><input type="checkbox" checked={selected.includes(x.id)} onChange={e=>setSelected(e.target.checked?[...selected,x.id]:selected.filter(v=>v!==x.id))}/></td><td>{i+1}</td><td><b>{x.name}</b></td><td>{x.phone||'N/A'}</td><td>{x.email&&x.email!=='N/A'?<a href={`mailto:${x.email}`}>{x.email}</a>:'N/A'}</td><td>{x.address||'N/A'}</td><td>{x.website&&x.website!=='N/A'?<a href={x.website} target="_blank" rel="noreferrer">Visit ↗</a>:'N/A'}</td><td>{x.category}</td><td>{google(x)?<a href={google(x)} target="_blank" rel="noreferrer">Open ↗</a>:'N/A'}</td><td><div className="row-actions"><button onClick={()=>setEditing({...x})}>Edit</button><button className="danger" onClick={()=>remove(x)}>Delete</button></div></td></tr>)}</tbody></table></div><p className="count">Showing {rows.length} results</p></section>{editing&&<div className="modal-backdrop"><form className="edit-modal" onSubmit={save}><div className="modal-title"><h2>Edit business</h2><button type="button" onClick={()=>setEditing(null)}>×</button></div><div className="edit-grid">{fields.map(([key,label])=><label key={key}><b>{label}</b>{key==='address'?<textarea value={editing[key]||''} onChange={e=>setEditing({...editing,[key]:e.target.value})}/>:<input required={key==='name'} value={editing[key]||''} onChange={e=>setEditing({...editing,[key]:e.target.value})}/>}</label>)}</div><div className="modal-actions"><button type="button" onClick={()=>setEditing(null)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Save changes'}</button></div></form></div>}</>
}
